# Numpy

We will be learning about some basic programming and data analysis using Numpy and Pandas. First up - NumPy

NumPy is the fundamental package for scientific computing in Python. It is used across many fields inc. Mathematics, Engineering, Finance, Data Science, Artificial Intelligence, Machine Learning etc. Most scientific computing libraries will build on NumPy.

Numpy provides functions to work with N-dimensional arrays and an assortment of routines for fast operations on such arrays: matrix mathematics, logical, shape manipulation, statistical operations, random simulation etc.

## Basic Numpy tools

<img src="https://matteding.github.io/images/broadcasting-3d-scalar.gif" width="400" height="400" align="left"/>


Here, we will exam some fairly simple tools in Numpy for the management of data and doing basic statistics. First, lets make sure numpy is imported:


In [109]:
import numpy as np

### Array creation and Indexing

In the cells below we will learn basic array creation and indexing


In [110]:
a = np.array([1, 2, 3])            # Create a simple array
print("Numpy Array 'a':\n")
print(type(a))                     # Prints type as recognised by Python
print(a.shape)                     # Prints its shape
print(a[0], a[1], a[2])            # Prints certain indexed values
a[0] = 5                           # Change an element of the array
print(a,"\n")                   


print("Numpy Array 'b':\n")
b = np.array([[1,2,3],[4,5,6]])    # Create an array with more 'complexity'
print(b.shape)
print(b)                     
print(b[0, 0], b[0, 1], b[1, 0])  


Numpy Array 'a':

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3] 

Numpy Array 'b':

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


### Array manipulation and mathematics
Where numpy gets really powerful is its efficiency in array manipulation and mathematics.

In [111]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y,'\n')
print(x * y,'\n') 

# numpy has many mathematical functions built in - accessed via dot notation
print(np.sqrt(x),'\n')
print(np.dot(x, y),'\n')
print(np.cross(x, y),'\n')

[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[19 22]
 [43 50]] 

[-4 -4] 



C:\Users\catz0911\AppData\Local\Temp\ipykernel_21700\15743206.py:10: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x, y),'\n')


Numpy also provides aggregation methods.

In [112]:
print(x.sum())  # sum over the entire matrix
print(y.mean(axis=1))  # mean of each row

10
[5.5 7.5]


## Activity
Your turn... <br>
Add comments that explain what your code is doing

#### 1) Create the following 3 x 4 array and call it 'c'

[[ 1  2  3  4] <br>
 [ 5  6  7  8] <br>
 [ 9 10 11 12]] <br>

In [113]:
# Create the following 3 x 4 array and call it 'c':
import numpy as np
c = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])     

#### 2) Print all values in rows 2 & 3

In [114]:
# Print all values in rows 2 & 3
print(c[1:3, :],'\n')

[[ 5  6  7  8]
 [ 9 10 11 12]] 



#### 3) Print the values in the 2nd row and in cols 1 & 3

In [115]:
# Print the values in the 2nd row and in cols 1 & 3
print(c[1,[0,2]],'\n')

[5 7] 



#### 4) Perform a scalar multiplication of c with 4

In [116]:
# Perform a scalar multiplication of c with 4
print(4*c)

[[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]]


#### 5) Transpose c

In [117]:
# Transpose c
print(c.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### 6) Reshape c to a 4 x 3 array
What is the difference between the transpose and reshape operations?

In [118]:
# Reshape c to a 4 x 3 array
print(c.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 7) Perform an element-wise multiplication of the reshaped c and transposed c

In [119]:
# Perform an element-wise multiplication of the reshaped c and transposed c
print((c.reshape(4,3)) * c.T)


[[  1  10  27]
 [  8  30  60]
 [ 21  56  99]
 [ 40  88 144]]


### Random
Random number generation plays a crucial role in configuring and evaluating many numerical and machine learning algorithms. Whether it's for randomly initializing weights in a neural network, splitting data into random subsets, or shuffling a dataset, the ability to generate random numbers (specifically repeatable pseudo-random numbers) is vital.

#### 8) Create a half hourly power profile for 1 year filled with random numbers between 0 and 50

In [120]:
# create a half hourly power profile for 1 year filled with random numbers between 0 and 50
d= np.random.randint(0,50,size=17520) #17520 half hours in a year i.e. 365*24*2
print(d)
# we used randint which creates an array of integers
#If we want a float array instead we could use:
#d= np.random.uniform(0,50,size=17520)


[48 49 11 ...  6 31 20]


#### 9) Reshape the array into daily half hour profiles

In [121]:
# reshape the array into daily half hour profiles
print(d.reshape(365,48) )

[[48 49 11 ... 42 45  8]
 [45 34 39 ... 34 21  1]
 [44 37 42 ... 30  3  2]
 ...
 [12 11 32 ... 28 21 14]
 [ 1 12  3 ... 24 17 42]
 [20 46 31 ...  6 31 20]]


#### 10) convert this array to energy

In [122]:
# convert to energy
energy = d.reshape(365,48) * 0.5  # energy = power*time   
print(energy)

[[24.  24.5  5.5 ... 21.  22.5  4. ]
 [22.5 17.  19.5 ... 17.  10.5  0.5]
 [22.  18.5 21.  ... 15.   1.5  1. ]
 ...
 [ 6.   5.5 16.  ... 14.  10.5  7. ]
 [ 0.5  6.   1.5 ... 12.   8.5 21. ]
 [10.  23.  15.5 ...  3.  15.5 10. ]]


  
#### Animation and Code Sources  

Numpy GIF: <a href="https://matteding.github.io/images/broadcasting-3d-scalar.gif">Matt Eding</a>  


In [123]:
print(np.shape(energy))

(365, 48)
